// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: qkms.proto

package qkms_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QkmsClient is the client API for Qkms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QkmsClient interface {
	// for all users
	ReadAccessKey(ctx context.Context, in *ReadAccessKeyRequest, opts ...grpc.CallOption) (*ReadAccessKeyReply, error)
	GenerateAccessKey(ctx context.Context, in *GenerateAccessKeyReply, opts ...grpc.CallOption) (*GenerateAccessKeyReply, error)
	CreateAccessKey(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*CreateAccessKeyReply, error)
	CreateKeyEncryptionKey(ctx context.Context, in *CreateKeyEncryptionKeyRequest, opts ...grpc.CallOption) (*CreateKeyEncryptionKeyReply, error)
	UpdateAccessKey(ctx context.Context, in *UpdateAccessKeyRequest, opts ...grpc.CallOption) (*UpdateAccessKeyReply, error)
	RotateAccessKey(ctx context.Context, in *RotateAccessKeyRequest, opts ...grpc.CallOption) (*RotateAccessKeyReply, error)
	GrantAccessKeyAuthorization(ctx context.Context, in *GrantAccessKeyAuthorizationRequest, opts ...grpc.CallOption) (*GrantAccessKeyAuthorizationReply, error)
	RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialReply, error)
	GetAccessKeyIndexs(ctx context.Context, in *GetAccessKeyIndexsRequest, opts ...grpc.CallOption) (*GetAccessKeyIndexsReply, error)
	// only for roots
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleReply, error)
	GrantNameSpaceForRole(ctx context.Context, in *GrantNameSpaceForRoleRequest, opts ...grpc.CallOption) (*GrantNameSpaceForRoleReply, error)
	GrantRoleForUser(ctx context.Context, in *GrantRoleForUserRequest, opts ...grpc.CallOption) (*GrantRoleForUserReply, error)
	GenerateCredential(ctx context.Context, in *GenerateCredentialRequest, opts ...grpc.CallOption) (*GenerateCredentialReply, error)
}

type qkmsClient struct {
	cc grpc.ClientConnInterface
}

func NewQkmsClient(cc grpc.ClientConnInterface) QkmsClient {
	return &qkmsClient{cc}
}

func (c *qkmsClient) ReadAccessKey(ctx context.Context, in *ReadAccessKeyRequest, opts ...grpc.CallOption) (*ReadAccessKeyReply, error) {
	out := new(ReadAccessKeyReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/ReadAccessKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GenerateAccessKey(ctx context.Context, in *GenerateAccessKeyReply, opts ...grpc.CallOption) (*GenerateAccessKeyReply, error) {
	out := new(GenerateAccessKeyReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/GenerateAccessKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateAccessKey(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*CreateAccessKeyReply, error) {
	out := new(CreateAccessKeyReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/CreateAccessKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateKeyEncryptionKey(ctx context.Context, in *CreateKeyEncryptionKeyRequest, opts ...grpc.CallOption) (*CreateKeyEncryptionKeyReply, error) {
	out := new(CreateKeyEncryptionKeyReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/CreateKeyEncryptionKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) UpdateAccessKey(ctx context.Context, in *UpdateAccessKeyRequest, opts ...grpc.CallOption) (*UpdateAccessKeyReply, error) {
	out := new(UpdateAccessKeyReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/UpdateAccessKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) RotateAccessKey(ctx context.Context, in *RotateAccessKeyRequest, opts ...grpc.CallOption) (*RotateAccessKeyReply, error) {
	out := new(RotateAccessKeyReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/RotateAccessKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GrantAccessKeyAuthorization(ctx context.Context, in *GrantAccessKeyAuthorizationRequest, opts ...grpc.CallOption) (*GrantAccessKeyAuthorizationReply, error) {
	out := new(GrantAccessKeyAuthorizationReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/GrantAccessKeyAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialReply, error) {
	out := new(RevokeCredentialReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/RevokeCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GetAccessKeyIndexs(ctx context.Context, in *GetAccessKeyIndexsRequest, opts ...grpc.CallOption) (*GetAccessKeyIndexsReply, error) {
	out := new(GetAccessKeyIndexsReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/GetAccessKeyIndexs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleReply, error) {
	out := new(CreateRoleReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GrantNameSpaceForRole(ctx context.Context, in *GrantNameSpaceForRoleRequest, opts ...grpc.CallOption) (*GrantNameSpaceForRoleReply, error) {
	out := new(GrantNameSpaceForRoleReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/GrantNameSpaceForRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GrantRoleForUser(ctx context.Context, in *GrantRoleForUserRequest, opts ...grpc.CallOption) (*GrantRoleForUserReply, error) {
	out := new(GrantRoleForUserReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/GrantRoleForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GenerateCredential(ctx context.Context, in *GenerateCredentialRequest, opts ...grpc.CallOption) (*GenerateCredentialReply, error) {
	out := new(GenerateCredentialReply)
	err := c.cc.Invoke(ctx, "/qkms_proto.qkms/GenerateCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QkmsServer is the server API for Qkms service.
// All implementations must embed UnimplementedQkmsServer
// for forward compatibility
type QkmsServer interface {
	// for all users
	ReadAccessKey(context.Context, *ReadAccessKeyRequest) (*ReadAccessKeyReply, error)
	GenerateAccessKey(context.Context, *GenerateAccessKeyReply) (*GenerateAccessKeyReply, error)
	CreateAccessKey(context.Context, *CreateAccessKeyRequest) (*CreateAccessKeyReply, error)
	CreateKeyEncryptionKey(context.Context, *CreateKeyEncryptionKeyRequest) (*CreateKeyEncryptionKeyReply, error)
	UpdateAccessKey(context.Context, *UpdateAccessKeyRequest) (*UpdateAccessKeyReply, error)
	RotateAccessKey(context.Context, *RotateAccessKeyRequest) (*RotateAccessKeyReply, error)
	GrantAccessKeyAuthorization(context.Context, *GrantAccessKeyAuthorizationRequest) (*GrantAccessKeyAuthorizationReply, error)
	RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialReply, error)
	GetAccessKeyIndexs(context.Context, *GetAccessKeyIndexsRequest) (*GetAccessKeyIndexsReply, error)
	// only for roots
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleReply, error)
	GrantNameSpaceForRole(context.Context, *GrantNameSpaceForRoleRequest) (*GrantNameSpaceForRoleReply, error)
	GrantRoleForUser(context.Context, *GrantRoleForUserRequest) (*GrantRoleForUserReply, error)
	GenerateCredential(context.Context, *GenerateCredentialRequest) (*GenerateCredentialReply, error)
	mustEmbedUnimplementedQkmsServer()
}

// UnimplementedQkmsServer must be embedded to have forward compatible implementations.
type UnimplementedQkmsServer struct {
}

func (UnimplementedQkmsServer) ReadAccessKey(context.Context, *ReadAccessKeyRequest) (*ReadAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAccessKey not implemented")
}
func (UnimplementedQkmsServer) GenerateAccessKey(context.Context, *GenerateAccessKeyReply) (*GenerateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessKey not implemented")
}
func (UnimplementedQkmsServer) CreateAccessKey(context.Context, *CreateAccessKeyRequest) (*CreateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccessKey not implemented")
}
func (UnimplementedQkmsServer) CreateKeyEncryptionKey(context.Context, *CreateKeyEncryptionKeyRequest) (*CreateKeyEncryptionKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyEncryptionKey not implemented")
}
func (UnimplementedQkmsServer) UpdateAccessKey(context.Context, *UpdateAccessKeyRequest) (*UpdateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccessKey not implemented")
}
func (UnimplementedQkmsServer) RotateAccessKey(context.Context, *RotateAccessKeyRequest) (*RotateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateAccessKey not implemented")
}
func (UnimplementedQkmsServer) GrantAccessKeyAuthorization(context.Context, *GrantAccessKeyAuthorizationRequest) (*GrantAccessKeyAuthorizationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantAccessKeyAuthorization not implemented")
}
func (UnimplementedQkmsServer) RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCredential not implemented")
}
func (UnimplementedQkmsServer) GetAccessKeyIndexs(context.Context, *GetAccessKeyIndexsRequest) (*GetAccessKeyIndexsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessKeyIndexs not implemented")
}
func (UnimplementedQkmsServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedQkmsServer) GrantNameSpaceForRole(context.Context, *GrantNameSpaceForRoleRequest) (*GrantNameSpaceForRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantNameSpaceForRole not implemented")
}
func (UnimplementedQkmsServer) GrantRoleForUser(context.Context, *GrantRoleForUserRequest) (*GrantRoleForUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantRoleForUser not implemented")
}
func (UnimplementedQkmsServer) GenerateCredential(context.Context, *GenerateCredentialRequest) (*GenerateCredentialReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCredential not implemented")
}
func (UnimplementedQkmsServer) mustEmbedUnimplementedQkmsServer() {}

// UnsafeQkmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QkmsServer will
// result in compilation errors.
type UnsafeQkmsServer interface {
	mustEmbedUnimplementedQkmsServer()
}

func RegisterQkmsServer(s grpc.ServiceRegistrar, srv QkmsServer) {
	s.RegisterService(&Qkms_ServiceDesc, srv)
}

func _Qkms_ReadAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).ReadAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/ReadAccessKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).ReadAccessKey(ctx, req.(*ReadAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GenerateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAccessKeyReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GenerateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/GenerateAccessKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GenerateAccessKey(ctx, req.(*GenerateAccessKeyReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/CreateAccessKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateAccessKey(ctx, req.(*CreateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateKeyEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyEncryptionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateKeyEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/CreateKeyEncryptionKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateKeyEncryptionKey(ctx, req.(*CreateKeyEncryptionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_UpdateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).UpdateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/UpdateAccessKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).UpdateAccessKey(ctx, req.(*UpdateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_RotateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).RotateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/RotateAccessKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).RotateAccessKey(ctx, req.(*RotateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GrantAccessKeyAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAccessKeyAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GrantAccessKeyAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/GrantAccessKeyAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GrantAccessKeyAuthorization(ctx, req.(*GrantAccessKeyAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_RevokeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).RevokeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/RevokeCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).RevokeCredential(ctx, req.(*RevokeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GetAccessKeyIndexs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessKeyIndexsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GetAccessKeyIndexs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/GetAccessKeyIndexs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GetAccessKeyIndexs(ctx, req.(*GetAccessKeyIndexsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GrantNameSpaceForRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantNameSpaceForRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GrantNameSpaceForRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/GrantNameSpaceForRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GrantNameSpaceForRole(ctx, req.(*GrantNameSpaceForRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GrantRoleForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRoleForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GrantRoleForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/GrantRoleForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GrantRoleForUser(ctx, req.(*GrantRoleForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GenerateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GenerateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qkms_proto.qkms/GenerateCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GenerateCredential(ctx, req.(*GenerateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Qkms_ServiceDesc is the grpc.ServiceDesc for Qkms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Qkms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qkms_proto.qkms",
	HandlerType: (*QkmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAccessKey",
			Handler:    _Qkms_ReadAccessKey_Handler,
		},
		{
			MethodName: "GenerateAccessKey",
			Handler:    _Qkms_GenerateAccessKey_Handler,
		},
		{
			MethodName: "CreateAccessKey",
			Handler:    _Qkms_CreateAccessKey_Handler,
		},
		{
			MethodName: "CreateKeyEncryptionKey",
			Handler:    _Qkms_CreateKeyEncryptionKey_Handler,
		},
		{
			MethodName: "UpdateAccessKey",
			Handler:    _Qkms_UpdateAccessKey_Handler,
		},
		{
			MethodName: "RotateAccessKey",
			Handler:    _Qkms_RotateAccessKey_Handler,
		},
		{
			MethodName: "GrantAccessKeyAuthorization",
			Handler:    _Qkms_GrantAccessKeyAuthorization_Handler,
		},
		{
			MethodName: "RevokeCredential",
			Handler:    _Qkms_RevokeCredential_Handler,
		},
		{
			MethodName: "GetAccessKeyIndexs",
			Handler:    _Qkms_GetAccessKeyIndexs_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _Qkms_CreateRole_Handler,
		},
		{
			MethodName: "GrantNameSpaceForRole",
			Handler:    _Qkms_GrantNameSpaceForRole_Handler,
		},
		{
			MethodName: "GrantRoleForUser",
			Handler:    _Qkms_GrantRoleForUser_Handler,
		},
		{
			MethodName: "GenerateCredential",
			Handler:    _Qkms_GenerateCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qkms.proto",
}
