// 以下的所有请求，写权限都是只有该密钥的拥有者，也就是grpc签名的appkey和密钥的appkey一致的才能拥有
// 读权限都是看权限授予表里面有没有授予对应appkey相应密钥的权限

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/qkms.proto

package qkms_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Qkms_ReadAccessKey_FullMethodName                   = "/qkms_proto.qkms/ReadAccessKey"
	Qkms_ReadReadableAccessKey_FullMethodName           = "/qkms_proto.qkms/ReadReadableAccessKey"
	Qkms_GenerateAccessKey_FullMethodName               = "/qkms_proto.qkms/GenerateAccessKey"
	Qkms_CreateReadableAccessKey_FullMethodName         = "/qkms_proto.qkms/CreateReadableAccessKey"
	Qkms_CreateAccessKey_FullMethodName                 = "/qkms_proto.qkms/CreateAccessKey"
	Qkms_CreateNameSpace_FullMethodName                 = "/qkms_proto.qkms/CreateNameSpace"
	Qkms_ReadNameSpace_FullMethodName                   = "/qkms_proto.qkms/ReadNameSpace"
	Qkms_UpdateAccessKey_FullMethodName                 = "/qkms_proto.qkms/UpdateAccessKey"
	Qkms_GrantAccessKeyAuthorization_FullMethodName     = "/qkms_proto.qkms/GrantAccessKeyAuthorization"
	Qkms_GetAccessKeyIndexs_FullMethodName              = "/qkms_proto.qkms/GetAccessKeyIndexs"
	Qkms_CreateRole_FullMethodName                      = "/qkms_proto.qkms/CreateRole"
	Qkms_GrantNameSpaceForRole_FullMethodName           = "/qkms_proto.qkms/GrantNameSpaceForRole"
	Qkms_GrantRoleForUser_FullMethodName                = "/qkms_proto.qkms/GrantRoleForUser"
	Qkms_RotateNameSpaceKeyEncryptionKey_FullMethodName = "/qkms_proto.qkms/RotateNameSpaceKeyEncryptionKey"
	Qkms_RotateAccessKey_FullMethodName                 = "/qkms_proto.qkms/RotateAccessKey"
	Qkms_UpdateNameSpaceInfo_FullMethodName             = "/qkms_proto.qkms/UpdateNameSpaceInfo"
	Qkms_CreateKeyEncryptionKey_FullMethodName          = "/qkms_proto.qkms/CreateKeyEncryptionKey"
	Qkms_GenerateCredential_FullMethodName              = "/qkms_proto.qkms/GenerateCredential"
	Qkms_RevokeCredential_FullMethodName                = "/qkms_proto.qkms/RevokeCredential"
)

// QkmsClient is the client API for Qkms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QkmsClient interface {
	// for all users
	ReadAccessKey(ctx context.Context, in *ReadAccessKeyRequest, opts ...grpc.CallOption) (*ReadAccessKeyReply, error)
	ReadReadableAccessKey(ctx context.Context, in *ReadReadableAccessKeyRequest, opts ...grpc.CallOption) (*ReadReadableAccessKeyReply, error)
	// access key can configure to auto ratate
	GenerateAccessKey(ctx context.Context, in *GenerateAccessKeyRequest, opts ...grpc.CallOption) (*GenerateAccessKeyReply, error)
	CreateReadableAccessKey(ctx context.Context, in *CreateReadableAccessKeyRequest, opts ...grpc.CallOption) (*CreateReadableAccessKeyReply, error)
	CreateAccessKey(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*CreateAccessKeyReply, error)
	CreateNameSpace(ctx context.Context, in *CreateNameSpaceRequest, opts ...grpc.CallOption) (*CreateNameSpaceReply, error)
	ReadNameSpace(ctx context.Context, in *ReadNameSpaceRequest, opts ...grpc.CallOption) (*ReadNameSpaceReply, error)
	UpdateAccessKey(ctx context.Context, in *UpdateAccessKeyRequest, opts ...grpc.CallOption) (*UpdateAccessKeyReply, error)
	GrantAccessKeyAuthorization(ctx context.Context, in *GrantAccessKeyAuthorizationRequest, opts ...grpc.CallOption) (*GrantAccessKeyAuthorizationReply, error)
	GetAccessKeyIndexs(ctx context.Context, in *GetAccessKeyIndexsRequest, opts ...grpc.CallOption) (*GetAccessKeyIndexsReply, error)
	// only for roots
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleReply, error)
	GrantNameSpaceForRole(ctx context.Context, in *GrantNameSpaceForRoleRequest, opts ...grpc.CallOption) (*GrantNameSpaceForRoleReply, error)
	GrantRoleForUser(ctx context.Context, in *GrantRoleForUserRequest, opts ...grpc.CallOption) (*GrantRoleForUserReply, error)
	// Any form rotation should only be perform by root
	RotateNameSpaceKeyEncryptionKey(ctx context.Context, in *RotateNameSpaceKeyEncryptionKeyRequest, opts ...grpc.CallOption) (*RotateNameSpaceKeyEncryptionKeyReply, error)
	RotateAccessKey(ctx context.Context, in *RotateAccessKeyRequest, opts ...grpc.CallOption) (*RotateAccessKeyReply, error)
	// root can update namespace owner app keys
	UpdateNameSpaceInfo(ctx context.Context, in *UpdateNameSpaceInfoRequest, opts ...grpc.CallOption) (*UpdateNameSpaceInfoReply, error)
	CreateKeyEncryptionKey(ctx context.Context, in *CreateKeyEncryptionKeyRequest, opts ...grpc.CallOption) (*CreateKeyEncryptionKeyReply, error)
	GenerateCredential(ctx context.Context, in *GenerateCredentialRequest, opts ...grpc.CallOption) (*GenerateCredentialReply, error)
	RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialReply, error)
}

type qkmsClient struct {
	cc grpc.ClientConnInterface
}

func NewQkmsClient(cc grpc.ClientConnInterface) QkmsClient {
	return &qkmsClient{cc}
}

func (c *qkmsClient) ReadAccessKey(ctx context.Context, in *ReadAccessKeyRequest, opts ...grpc.CallOption) (*ReadAccessKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAccessKeyReply)
	err := c.cc.Invoke(ctx, Qkms_ReadAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) ReadReadableAccessKey(ctx context.Context, in *ReadReadableAccessKeyRequest, opts ...grpc.CallOption) (*ReadReadableAccessKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadReadableAccessKeyReply)
	err := c.cc.Invoke(ctx, Qkms_ReadReadableAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GenerateAccessKey(ctx context.Context, in *GenerateAccessKeyRequest, opts ...grpc.CallOption) (*GenerateAccessKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAccessKeyReply)
	err := c.cc.Invoke(ctx, Qkms_GenerateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateReadableAccessKey(ctx context.Context, in *CreateReadableAccessKeyRequest, opts ...grpc.CallOption) (*CreateReadableAccessKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReadableAccessKeyReply)
	err := c.cc.Invoke(ctx, Qkms_CreateReadableAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateAccessKey(ctx context.Context, in *CreateAccessKeyRequest, opts ...grpc.CallOption) (*CreateAccessKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccessKeyReply)
	err := c.cc.Invoke(ctx, Qkms_CreateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateNameSpace(ctx context.Context, in *CreateNameSpaceRequest, opts ...grpc.CallOption) (*CreateNameSpaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNameSpaceReply)
	err := c.cc.Invoke(ctx, Qkms_CreateNameSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) ReadNameSpace(ctx context.Context, in *ReadNameSpaceRequest, opts ...grpc.CallOption) (*ReadNameSpaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadNameSpaceReply)
	err := c.cc.Invoke(ctx, Qkms_ReadNameSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) UpdateAccessKey(ctx context.Context, in *UpdateAccessKeyRequest, opts ...grpc.CallOption) (*UpdateAccessKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAccessKeyReply)
	err := c.cc.Invoke(ctx, Qkms_UpdateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GrantAccessKeyAuthorization(ctx context.Context, in *GrantAccessKeyAuthorizationRequest, opts ...grpc.CallOption) (*GrantAccessKeyAuthorizationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantAccessKeyAuthorizationReply)
	err := c.cc.Invoke(ctx, Qkms_GrantAccessKeyAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GetAccessKeyIndexs(ctx context.Context, in *GetAccessKeyIndexsRequest, opts ...grpc.CallOption) (*GetAccessKeyIndexsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccessKeyIndexsReply)
	err := c.cc.Invoke(ctx, Qkms_GetAccessKeyIndexs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleReply)
	err := c.cc.Invoke(ctx, Qkms_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GrantNameSpaceForRole(ctx context.Context, in *GrantNameSpaceForRoleRequest, opts ...grpc.CallOption) (*GrantNameSpaceForRoleReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantNameSpaceForRoleReply)
	err := c.cc.Invoke(ctx, Qkms_GrantNameSpaceForRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GrantRoleForUser(ctx context.Context, in *GrantRoleForUserRequest, opts ...grpc.CallOption) (*GrantRoleForUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantRoleForUserReply)
	err := c.cc.Invoke(ctx, Qkms_GrantRoleForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) RotateNameSpaceKeyEncryptionKey(ctx context.Context, in *RotateNameSpaceKeyEncryptionKeyRequest, opts ...grpc.CallOption) (*RotateNameSpaceKeyEncryptionKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateNameSpaceKeyEncryptionKeyReply)
	err := c.cc.Invoke(ctx, Qkms_RotateNameSpaceKeyEncryptionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) RotateAccessKey(ctx context.Context, in *RotateAccessKeyRequest, opts ...grpc.CallOption) (*RotateAccessKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateAccessKeyReply)
	err := c.cc.Invoke(ctx, Qkms_RotateAccessKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) UpdateNameSpaceInfo(ctx context.Context, in *UpdateNameSpaceInfoRequest, opts ...grpc.CallOption) (*UpdateNameSpaceInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNameSpaceInfoReply)
	err := c.cc.Invoke(ctx, Qkms_UpdateNameSpaceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) CreateKeyEncryptionKey(ctx context.Context, in *CreateKeyEncryptionKeyRequest, opts ...grpc.CallOption) (*CreateKeyEncryptionKeyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyEncryptionKeyReply)
	err := c.cc.Invoke(ctx, Qkms_CreateKeyEncryptionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) GenerateCredential(ctx context.Context, in *GenerateCredentialRequest, opts ...grpc.CallOption) (*GenerateCredentialReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCredentialReply)
	err := c.cc.Invoke(ctx, Qkms_GenerateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qkmsClient) RevokeCredential(ctx context.Context, in *RevokeCredentialRequest, opts ...grpc.CallOption) (*RevokeCredentialReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCredentialReply)
	err := c.cc.Invoke(ctx, Qkms_RevokeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QkmsServer is the server API for Qkms service.
// All implementations must embed UnimplementedQkmsServer
// for forward compatibility.
type QkmsServer interface {
	// for all users
	ReadAccessKey(context.Context, *ReadAccessKeyRequest) (*ReadAccessKeyReply, error)
	ReadReadableAccessKey(context.Context, *ReadReadableAccessKeyRequest) (*ReadReadableAccessKeyReply, error)
	// access key can configure to auto ratate
	GenerateAccessKey(context.Context, *GenerateAccessKeyRequest) (*GenerateAccessKeyReply, error)
	CreateReadableAccessKey(context.Context, *CreateReadableAccessKeyRequest) (*CreateReadableAccessKeyReply, error)
	CreateAccessKey(context.Context, *CreateAccessKeyRequest) (*CreateAccessKeyReply, error)
	CreateNameSpace(context.Context, *CreateNameSpaceRequest) (*CreateNameSpaceReply, error)
	ReadNameSpace(context.Context, *ReadNameSpaceRequest) (*ReadNameSpaceReply, error)
	UpdateAccessKey(context.Context, *UpdateAccessKeyRequest) (*UpdateAccessKeyReply, error)
	GrantAccessKeyAuthorization(context.Context, *GrantAccessKeyAuthorizationRequest) (*GrantAccessKeyAuthorizationReply, error)
	GetAccessKeyIndexs(context.Context, *GetAccessKeyIndexsRequest) (*GetAccessKeyIndexsReply, error)
	// only for roots
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleReply, error)
	GrantNameSpaceForRole(context.Context, *GrantNameSpaceForRoleRequest) (*GrantNameSpaceForRoleReply, error)
	GrantRoleForUser(context.Context, *GrantRoleForUserRequest) (*GrantRoleForUserReply, error)
	// Any form rotation should only be perform by root
	RotateNameSpaceKeyEncryptionKey(context.Context, *RotateNameSpaceKeyEncryptionKeyRequest) (*RotateNameSpaceKeyEncryptionKeyReply, error)
	RotateAccessKey(context.Context, *RotateAccessKeyRequest) (*RotateAccessKeyReply, error)
	// root can update namespace owner app keys
	UpdateNameSpaceInfo(context.Context, *UpdateNameSpaceInfoRequest) (*UpdateNameSpaceInfoReply, error)
	CreateKeyEncryptionKey(context.Context, *CreateKeyEncryptionKeyRequest) (*CreateKeyEncryptionKeyReply, error)
	GenerateCredential(context.Context, *GenerateCredentialRequest) (*GenerateCredentialReply, error)
	RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialReply, error)
	mustEmbedUnimplementedQkmsServer()
}

// UnimplementedQkmsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQkmsServer struct{}

func (UnimplementedQkmsServer) ReadAccessKey(context.Context, *ReadAccessKeyRequest) (*ReadAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAccessKey not implemented")
}
func (UnimplementedQkmsServer) ReadReadableAccessKey(context.Context, *ReadReadableAccessKeyRequest) (*ReadReadableAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadReadableAccessKey not implemented")
}
func (UnimplementedQkmsServer) GenerateAccessKey(context.Context, *GenerateAccessKeyRequest) (*GenerateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccessKey not implemented")
}
func (UnimplementedQkmsServer) CreateReadableAccessKey(context.Context, *CreateReadableAccessKeyRequest) (*CreateReadableAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReadableAccessKey not implemented")
}
func (UnimplementedQkmsServer) CreateAccessKey(context.Context, *CreateAccessKeyRequest) (*CreateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccessKey not implemented")
}
func (UnimplementedQkmsServer) CreateNameSpace(context.Context, *CreateNameSpaceRequest) (*CreateNameSpaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNameSpace not implemented")
}
func (UnimplementedQkmsServer) ReadNameSpace(context.Context, *ReadNameSpaceRequest) (*ReadNameSpaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadNameSpace not implemented")
}
func (UnimplementedQkmsServer) UpdateAccessKey(context.Context, *UpdateAccessKeyRequest) (*UpdateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccessKey not implemented")
}
func (UnimplementedQkmsServer) GrantAccessKeyAuthorization(context.Context, *GrantAccessKeyAuthorizationRequest) (*GrantAccessKeyAuthorizationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantAccessKeyAuthorization not implemented")
}
func (UnimplementedQkmsServer) GetAccessKeyIndexs(context.Context, *GetAccessKeyIndexsRequest) (*GetAccessKeyIndexsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessKeyIndexs not implemented")
}
func (UnimplementedQkmsServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedQkmsServer) GrantNameSpaceForRole(context.Context, *GrantNameSpaceForRoleRequest) (*GrantNameSpaceForRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantNameSpaceForRole not implemented")
}
func (UnimplementedQkmsServer) GrantRoleForUser(context.Context, *GrantRoleForUserRequest) (*GrantRoleForUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantRoleForUser not implemented")
}
func (UnimplementedQkmsServer) RotateNameSpaceKeyEncryptionKey(context.Context, *RotateNameSpaceKeyEncryptionKeyRequest) (*RotateNameSpaceKeyEncryptionKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateNameSpaceKeyEncryptionKey not implemented")
}
func (UnimplementedQkmsServer) RotateAccessKey(context.Context, *RotateAccessKeyRequest) (*RotateAccessKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateAccessKey not implemented")
}
func (UnimplementedQkmsServer) UpdateNameSpaceInfo(context.Context, *UpdateNameSpaceInfoRequest) (*UpdateNameSpaceInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNameSpaceInfo not implemented")
}
func (UnimplementedQkmsServer) CreateKeyEncryptionKey(context.Context, *CreateKeyEncryptionKeyRequest) (*CreateKeyEncryptionKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyEncryptionKey not implemented")
}
func (UnimplementedQkmsServer) GenerateCredential(context.Context, *GenerateCredentialRequest) (*GenerateCredentialReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCredential not implemented")
}
func (UnimplementedQkmsServer) RevokeCredential(context.Context, *RevokeCredentialRequest) (*RevokeCredentialReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCredential not implemented")
}
func (UnimplementedQkmsServer) mustEmbedUnimplementedQkmsServer() {}
func (UnimplementedQkmsServer) testEmbeddedByValue()              {}

// UnsafeQkmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QkmsServer will
// result in compilation errors.
type UnsafeQkmsServer interface {
	mustEmbedUnimplementedQkmsServer()
}

func RegisterQkmsServer(s grpc.ServiceRegistrar, srv QkmsServer) {
	// If the following call pancis, it indicates UnimplementedQkmsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Qkms_ServiceDesc, srv)
}

func _Qkms_ReadAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).ReadAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_ReadAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).ReadAccessKey(ctx, req.(*ReadAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_ReadReadableAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadReadableAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).ReadReadableAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_ReadReadableAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).ReadReadableAccessKey(ctx, req.(*ReadReadableAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GenerateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GenerateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_GenerateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GenerateAccessKey(ctx, req.(*GenerateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateReadableAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReadableAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateReadableAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_CreateReadableAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateReadableAccessKey(ctx, req.(*CreateReadableAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_CreateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateAccessKey(ctx, req.(*CreateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateNameSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNameSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateNameSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_CreateNameSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateNameSpace(ctx, req.(*CreateNameSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_ReadNameSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNameSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).ReadNameSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_ReadNameSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).ReadNameSpace(ctx, req.(*ReadNameSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_UpdateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).UpdateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_UpdateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).UpdateAccessKey(ctx, req.(*UpdateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GrantAccessKeyAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAccessKeyAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GrantAccessKeyAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_GrantAccessKeyAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GrantAccessKeyAuthorization(ctx, req.(*GrantAccessKeyAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GetAccessKeyIndexs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessKeyIndexsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GetAccessKeyIndexs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_GetAccessKeyIndexs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GetAccessKeyIndexs(ctx, req.(*GetAccessKeyIndexsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GrantNameSpaceForRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantNameSpaceForRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GrantNameSpaceForRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_GrantNameSpaceForRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GrantNameSpaceForRole(ctx, req.(*GrantNameSpaceForRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GrantRoleForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRoleForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GrantRoleForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_GrantRoleForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GrantRoleForUser(ctx, req.(*GrantRoleForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_RotateNameSpaceKeyEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateNameSpaceKeyEncryptionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).RotateNameSpaceKeyEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_RotateNameSpaceKeyEncryptionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).RotateNameSpaceKeyEncryptionKey(ctx, req.(*RotateNameSpaceKeyEncryptionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_RotateAccessKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateAccessKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).RotateAccessKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_RotateAccessKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).RotateAccessKey(ctx, req.(*RotateAccessKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_UpdateNameSpaceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNameSpaceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).UpdateNameSpaceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_UpdateNameSpaceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).UpdateNameSpaceInfo(ctx, req.(*UpdateNameSpaceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_CreateKeyEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyEncryptionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).CreateKeyEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_CreateKeyEncryptionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).CreateKeyEncryptionKey(ctx, req.(*CreateKeyEncryptionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_GenerateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).GenerateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_GenerateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).GenerateCredential(ctx, req.(*GenerateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qkms_RevokeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QkmsServer).RevokeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qkms_RevokeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QkmsServer).RevokeCredential(ctx, req.(*RevokeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Qkms_ServiceDesc is the grpc.ServiceDesc for Qkms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Qkms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qkms_proto.qkms",
	HandlerType: (*QkmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAccessKey",
			Handler:    _Qkms_ReadAccessKey_Handler,
		},
		{
			MethodName: "ReadReadableAccessKey",
			Handler:    _Qkms_ReadReadableAccessKey_Handler,
		},
		{
			MethodName: "GenerateAccessKey",
			Handler:    _Qkms_GenerateAccessKey_Handler,
		},
		{
			MethodName: "CreateReadableAccessKey",
			Handler:    _Qkms_CreateReadableAccessKey_Handler,
		},
		{
			MethodName: "CreateAccessKey",
			Handler:    _Qkms_CreateAccessKey_Handler,
		},
		{
			MethodName: "CreateNameSpace",
			Handler:    _Qkms_CreateNameSpace_Handler,
		},
		{
			MethodName: "ReadNameSpace",
			Handler:    _Qkms_ReadNameSpace_Handler,
		},
		{
			MethodName: "UpdateAccessKey",
			Handler:    _Qkms_UpdateAccessKey_Handler,
		},
		{
			MethodName: "GrantAccessKeyAuthorization",
			Handler:    _Qkms_GrantAccessKeyAuthorization_Handler,
		},
		{
			MethodName: "GetAccessKeyIndexs",
			Handler:    _Qkms_GetAccessKeyIndexs_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _Qkms_CreateRole_Handler,
		},
		{
			MethodName: "GrantNameSpaceForRole",
			Handler:    _Qkms_GrantNameSpaceForRole_Handler,
		},
		{
			MethodName: "GrantRoleForUser",
			Handler:    _Qkms_GrantRoleForUser_Handler,
		},
		{
			MethodName: "RotateNameSpaceKeyEncryptionKey",
			Handler:    _Qkms_RotateNameSpaceKeyEncryptionKey_Handler,
		},
		{
			MethodName: "RotateAccessKey",
			Handler:    _Qkms_RotateAccessKey_Handler,
		},
		{
			MethodName: "UpdateNameSpaceInfo",
			Handler:    _Qkms_UpdateNameSpaceInfo_Handler,
		},
		{
			MethodName: "CreateKeyEncryptionKey",
			Handler:    _Qkms_CreateKeyEncryptionKey_Handler,
		},
		{
			MethodName: "GenerateCredential",
			Handler:    _Qkms_GenerateCredential_Handler,
		},
		{
			MethodName: "RevokeCredential",
			Handler:    _Qkms_RevokeCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qkms.proto",
}
