// 以下的所有请求，写权限都是只有该密钥的拥有者，也就是grpc签名的appkey和密钥的appkey一致的才能拥有
// 读权限都是看权限授予表里面有没有授予对应appkey相应密钥的权限

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/qkms.proto

package qkms_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadAccessKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAccessKeyRequest) Reset() {
	*x = ReadAccessKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAccessKeyRequest) ProtoMessage() {}

func (x *ReadAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*ReadAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{0}
}

func (x *ReadAccessKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *ReadAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadAccessKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ReadAccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	NameSpace     string                 `protobuf:"bytes,3,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	AKPlaintext   string                 `protobuf:"bytes,5,opt,name=AKPlaintext,proto3" json:"AKPlaintext,omitempty"`
	KeyType       string                 `protobuf:"bytes,6,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	Environment   string                 `protobuf:"bytes,7,opt,name=Environment,proto3" json:"Environment,omitempty"`
	Version       uint64                 `protobuf:"varint,8,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAccessKeyReply) Reset() {
	*x = ReadAccessKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAccessKeyReply) ProtoMessage() {}

func (x *ReadAccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAccessKeyReply.ProtoReflect.Descriptor instead.
func (*ReadAccessKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{1}
}

func (x *ReadAccessKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ReadAccessKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ReadAccessKeyReply) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *ReadAccessKeyReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadAccessKeyReply) GetAKPlaintext() string {
	if x != nil {
		return x.AKPlaintext
	}
	return ""
}

func (x *ReadAccessKeyReply) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *ReadAccessKeyReply) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ReadAccessKeyReply) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReadReadableAccessKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReadableAccessKeyRequest) Reset() {
	*x = ReadReadableAccessKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReadableAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReadableAccessKeyRequest) ProtoMessage() {}

func (x *ReadReadableAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReadableAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*ReadReadableAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{2}
}

func (x *ReadReadableAccessKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *ReadReadableAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadReadableAccessKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ReadReadableAccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	NameSpace     string                 `protobuf:"bytes,3,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	AKPlaintext   string                 `protobuf:"bytes,5,opt,name=AKPlaintext,proto3" json:"AKPlaintext,omitempty"`
	KeyType       string                 `protobuf:"bytes,6,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	Environment   string                 `protobuf:"bytes,7,opt,name=Environment,proto3" json:"Environment,omitempty"`
	Version       uint64                 `protobuf:"varint,8,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadReadableAccessKeyReply) Reset() {
	*x = ReadReadableAccessKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadReadableAccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadReadableAccessKeyReply) ProtoMessage() {}

func (x *ReadReadableAccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadReadableAccessKeyReply.ProtoReflect.Descriptor instead.
func (*ReadReadableAccessKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{3}
}

func (x *ReadReadableAccessKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ReadReadableAccessKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ReadReadableAccessKeyReply) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *ReadReadableAccessKeyReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadReadableAccessKeyReply) GetAKPlaintext() string {
	if x != nil {
		return x.AKPlaintext
	}
	return ""
}

func (x *ReadReadableAccessKeyReply) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *ReadReadableAccessKeyReply) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ReadReadableAccessKeyReply) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GenerateAccessKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NameSpace      string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	KeyType        string                 `protobuf:"bytes,3,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	Environment    string                 `protobuf:"bytes,4,opt,name=Environment,proto3" json:"Environment,omitempty"`
	LifeTime       uint64                 `protobuf:"varint,5,opt,name=LifeTime,proto3" json:"LifeTime,omitempty"`
	RotateDuration uint64                 `protobuf:"varint,6,opt,name=RotateDuration,proto3" json:"RotateDuration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateAccessKeyRequest) Reset() {
	*x = GenerateAccessKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAccessKeyRequest) ProtoMessage() {}

func (x *GenerateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateAccessKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *GenerateAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateAccessKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *GenerateAccessKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *GenerateAccessKeyRequest) GetLifeTime() uint64 {
	if x != nil {
		return x.LifeTime
	}
	return 0
}

func (x *GenerateAccessKeyRequest) GetRotateDuration() uint64 {
	if x != nil {
		return x.RotateDuration
	}
	return 0
}

type GenerateAccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAccessKeyReply) Reset() {
	*x = GenerateAccessKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAccessKeyReply) ProtoMessage() {}

func (x *GenerateAccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAccessKeyReply.ProtoReflect.Descriptor instead.
func (*GenerateAccessKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateAccessKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GenerateAccessKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 首先key_type需要和数据库里面的key_type一致。
type RotateAccessKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	KeyType       string                 `protobuf:"bytes,3,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAccessKeyRequest) Reset() {
	*x = RotateAccessKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAccessKeyRequest) ProtoMessage() {}

func (x *RotateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{6}
}

func (x *RotateAccessKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *RotateAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RotateAccessKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *RotateAccessKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type RotateAccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAccessKeyReply) Reset() {
	*x = RotateAccessKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAccessKeyReply) ProtoMessage() {}

func (x *RotateAccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAccessKeyReply.ProtoReflect.Descriptor instead.
func (*RotateAccessKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{7}
}

func (x *RotateAccessKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *RotateAccessKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateAccessKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NameSpace      string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	AKPlaintext    string                 `protobuf:"bytes,3,opt,name=AKPlaintext,proto3" json:"AKPlaintext,omitempty"`
	KeyType        string                 `protobuf:"bytes,4,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	Environment    string                 `protobuf:"bytes,5,opt,name=Environment,proto3" json:"Environment,omitempty"`
	LifeTime       uint64                 `protobuf:"varint,6,opt,name=LifeTime,proto3" json:"LifeTime,omitempty"`
	RotateDuration uint64                 `protobuf:"varint,7,opt,name=RotateDuration,proto3" json:"RotateDuration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccessKeyRequest) Reset() {
	*x = CreateAccessKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessKeyRequest) ProtoMessage() {}

func (x *CreateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAccessKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *CreateAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccessKeyRequest) GetAKPlaintext() string {
	if x != nil {
		return x.AKPlaintext
	}
	return ""
}

func (x *CreateAccessKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *CreateAccessKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CreateAccessKeyRequest) GetLifeTime() uint64 {
	if x != nil {
		return x.LifeTime
	}
	return 0
}

func (x *CreateAccessKeyRequest) GetRotateDuration() uint64 {
	if x != nil {
		return x.RotateDuration
	}
	return 0
}

type CreateAccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessKeyReply) Reset() {
	*x = CreateAccessKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessKeyReply) ProtoMessage() {}

func (x *CreateAccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessKeyReply.ProtoReflect.Descriptor instead.
func (*CreateAccessKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAccessKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateAccessKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateReadableAccessKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NameSpace      string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	AKPlaintext    string                 `protobuf:"bytes,3,opt,name=AKPlaintext,proto3" json:"AKPlaintext,omitempty"`
	KeyType        string                 `protobuf:"bytes,4,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	Environment    string                 `protobuf:"bytes,5,opt,name=Environment,proto3" json:"Environment,omitempty"`
	LifeTime       uint64                 `protobuf:"varint,6,opt,name=LifeTime,proto3" json:"LifeTime,omitempty"`
	RotateDuration uint64                 `protobuf:"varint,7,opt,name=RotateDuration,proto3" json:"RotateDuration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReadableAccessKeyRequest) Reset() {
	*x = CreateReadableAccessKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReadableAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadableAccessKeyRequest) ProtoMessage() {}

func (x *CreateReadableAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadableAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateReadableAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{10}
}

func (x *CreateReadableAccessKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *CreateReadableAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReadableAccessKeyRequest) GetAKPlaintext() string {
	if x != nil {
		return x.AKPlaintext
	}
	return ""
}

func (x *CreateReadableAccessKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *CreateReadableAccessKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CreateReadableAccessKeyRequest) GetLifeTime() uint64 {
	if x != nil {
		return x.LifeTime
	}
	return 0
}

func (x *CreateReadableAccessKeyRequest) GetRotateDuration() uint64 {
	if x != nil {
		return x.RotateDuration
	}
	return 0
}

type CreateReadableAccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReadableAccessKeyReply) Reset() {
	*x = CreateReadableAccessKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReadableAccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadableAccessKeyReply) ProtoMessage() {}

func (x *CreateReadableAccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadableAccessKeyReply.ProtoReflect.Descriptor instead.
func (*CreateReadableAccessKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{11}
}

func (x *CreateReadableAccessKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateReadableAccessKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

// 首先key_type需要和数据库里面的key_type一致。
type UpdateAccessKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	KeyType       string                 `protobuf:"bytes,3,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	AKPlaintext   string                 `protobuf:"bytes,4,opt,name=AKPlaintext,proto3" json:"AKPlaintext,omitempty"`
	Environment   string                 `protobuf:"bytes,5,opt,name=Environment,proto3" json:"Environment,omitempty"`
	Version       uint64                 `protobuf:"varint,6,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessKeyRequest) Reset() {
	*x = UpdateAccessKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessKeyRequest) ProtoMessage() {}

func (x *UpdateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateAccessKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *UpdateAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAccessKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *UpdateAccessKeyRequest) GetAKPlaintext() string {
	if x != nil {
		return x.AKPlaintext
	}
	return ""
}

func (x *UpdateAccessKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *UpdateAccessKeyRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateAccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessKeyReply) Reset() {
	*x = UpdateAccessKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessKeyReply) ProtoMessage() {}

func (x *UpdateAccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessKeyReply.ProtoReflect.Descriptor instead.
func (*UpdateAccessKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAccessKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *UpdateAccessKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateOrUpdateKeyAuthorizationPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=Environment,proto3" json:"Environment,omitempty"`
	UserAppkey    string                 `protobuf:"bytes,4,opt,name=UserAppkey,proto3" json:"UserAppkey,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=Action,proto3" json:"Action,omitempty"`
	Effect        string                 `protobuf:"bytes,6,opt,name=Effect,proto3" json:"Effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) Reset() {
	*x = CreateOrUpdateKeyAuthorizationPolicyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateKeyAuthorizationPolicyRequest) ProtoMessage() {}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateKeyAuthorizationPolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateKeyAuthorizationPolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) GetUserAppkey() string {
	if x != nil {
		return x.UserAppkey
	}
	return ""
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreateOrUpdateKeyAuthorizationPolicyRequest) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

type CreateOrUpdateKeyAuthorizationPolicyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateKeyAuthorizationPolicyReply) Reset() {
	*x = CreateOrUpdateKeyAuthorizationPolicyReply{}
	mi := &file_proto_qkms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateKeyAuthorizationPolicyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateKeyAuthorizationPolicyReply) ProtoMessage() {}

func (x *CreateOrUpdateKeyAuthorizationPolicyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateKeyAuthorizationPolicyReply.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateKeyAuthorizationPolicyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{15}
}

func (x *CreateOrUpdateKeyAuthorizationPolicyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateOrUpdateKeyAuthorizationPolicyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateNameSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNameSpaceRequest) Reset() {
	*x = CreateNameSpaceRequest{}
	mi := &file_proto_qkms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNameSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNameSpaceRequest) ProtoMessage() {}

func (x *CreateNameSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNameSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNameSpaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{16}
}

func (x *CreateNameSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNameSpaceRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type CreateNameSpaceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNameSpaceReply) Reset() {
	*x = CreateNameSpaceReply{}
	mi := &file_proto_qkms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNameSpaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNameSpaceReply) ProtoMessage() {}

func (x *CreateNameSpaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNameSpaceReply.ProtoReflect.Descriptor instead.
func (*CreateNameSpaceReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{17}
}

func (x *CreateNameSpaceReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateNameSpaceReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type RotateNameSpaceKeyEncryptionKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateNameSpaceKeyEncryptionKeyRequest) Reset() {
	*x = RotateNameSpaceKeyEncryptionKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNameSpaceKeyEncryptionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNameSpaceKeyEncryptionKeyRequest) ProtoMessage() {}

func (x *RotateNameSpaceKeyEncryptionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNameSpaceKeyEncryptionKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateNameSpaceKeyEncryptionKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{18}
}

func (x *RotateNameSpaceKeyEncryptionKeyRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *RotateNameSpaceKeyEncryptionKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type RotateNameSpaceKeyEncryptionKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateNameSpaceKeyEncryptionKeyReply) Reset() {
	*x = RotateNameSpaceKeyEncryptionKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNameSpaceKeyEncryptionKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNameSpaceKeyEncryptionKeyReply) ProtoMessage() {}

func (x *RotateNameSpaceKeyEncryptionKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNameSpaceKeyEncryptionKeyReply.ProtoReflect.Descriptor instead.
func (*RotateNameSpaceKeyEncryptionKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{19}
}

func (x *RotateNameSpaceKeyEncryptionKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *RotateNameSpaceKeyEncryptionKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateKeyEncryptionKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=Environment,proto3" json:"Environment,omitempty"`
	KeyType       string                 `protobuf:"bytes,3,opt,name=KeyType,proto3" json:"KeyType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyEncryptionKeyRequest) Reset() {
	*x = CreateKeyEncryptionKeyRequest{}
	mi := &file_proto_qkms_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyEncryptionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyEncryptionKeyRequest) ProtoMessage() {}

func (x *CreateKeyEncryptionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyEncryptionKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyEncryptionKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{20}
}

func (x *CreateKeyEncryptionKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKeyEncryptionKeyRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CreateKeyEncryptionKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

type CreateKeyEncryptionKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyEncryptionKeyReply) Reset() {
	*x = CreateKeyEncryptionKeyReply{}
	mi := &file_proto_qkms_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyEncryptionKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyEncryptionKeyReply) ProtoMessage() {}

func (x *CreateKeyEncryptionKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyEncryptionKeyReply.ProtoReflect.Descriptor instead.
func (*CreateKeyEncryptionKeyReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{21}
}

func (x *CreateKeyEncryptionKeyReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateKeyEncryptionKeyReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ReadNameSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadNameSpaceRequest) Reset() {
	*x = ReadNameSpaceRequest{}
	mi := &file_proto_qkms_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadNameSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNameSpaceRequest) ProtoMessage() {}

func (x *ReadNameSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNameSpaceRequest.ProtoReflect.Descriptor instead.
func (*ReadNameSpaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{22}
}

func (x *ReadNameSpaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadNameSpaceRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ReadNameSpaceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	KEK           string                 `protobuf:"bytes,4,opt,name=KEK,proto3" json:"KEK,omitempty"`
	Environment   string                 `protobuf:"bytes,5,opt,name=Environment,proto3" json:"Environment,omitempty"`
	OwnerAppkey   string                 `protobuf:"bytes,6,opt,name=OwnerAppkey,proto3" json:"OwnerAppkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadNameSpaceReply) Reset() {
	*x = ReadNameSpaceReply{}
	mi := &file_proto_qkms_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadNameSpaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadNameSpaceReply) ProtoMessage() {}

func (x *ReadNameSpaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadNameSpaceReply.ProtoReflect.Descriptor instead.
func (*ReadNameSpaceReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{23}
}

func (x *ReadNameSpaceReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ReadNameSpaceReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ReadNameSpaceReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadNameSpaceReply) GetKEK() string {
	if x != nil {
		return x.KEK
	}
	return ""
}

func (x *ReadNameSpaceReply) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ReadNameSpaceReply) GetOwnerAppkey() string {
	if x != nil {
		return x.OwnerAppkey
	}
	return ""
}

type UpdateNameSpaceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=Environment,proto3" json:"Environment,omitempty"`
	KEK           string                 `protobuf:"bytes,3,opt,name=KEK,proto3" json:"KEK,omitempty"`
	OwnerAppkey   string                 `protobuf:"bytes,4,opt,name=OwnerAppkey,proto3" json:"OwnerAppkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNameSpaceInfoRequest) Reset() {
	*x = UpdateNameSpaceInfoRequest{}
	mi := &file_proto_qkms_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNameSpaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNameSpaceInfoRequest) ProtoMessage() {}

func (x *UpdateNameSpaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNameSpaceInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateNameSpaceInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateNameSpaceInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNameSpaceInfoRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *UpdateNameSpaceInfoRequest) GetKEK() string {
	if x != nil {
		return x.KEK
	}
	return ""
}

func (x *UpdateNameSpaceInfoRequest) GetOwnerAppkey() string {
	if x != nil {
		return x.OwnerAppkey
	}
	return ""
}

type UpdateNameSpaceInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNameSpaceInfoReply) Reset() {
	*x = UpdateNameSpaceInfoReply{}
	mi := &file_proto_qkms_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNameSpaceInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNameSpaceInfoReply) ProtoMessage() {}

func (x *UpdateNameSpaceInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNameSpaceInfoReply.ProtoReflect.Descriptor instead.
func (*UpdateNameSpaceInfoReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateNameSpaceInfoReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *UpdateNameSpaceInfoReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_qkms_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{26}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReply) Reset() {
	*x = CreateRoleReply{}
	mi := &file_proto_qkms_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReply) ProtoMessage() {}

func (x *CreateRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReply.ProtoReflect.Descriptor instead.
func (*CreateRoleReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{27}
}

func (x *CreateRoleReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateRoleReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GrantAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAdminRequest) Reset() {
	*x = GrantAdminRequest{}
	mi := &file_proto_qkms_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAdminRequest) ProtoMessage() {}

func (x *GrantAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAdminRequest.ProtoReflect.Descriptor instead.
func (*GrantAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{28}
}

func (x *GrantAdminRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type GrantAdminReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAdminReply) Reset() {
	*x = GrantAdminReply{}
	mi := &file_proto_qkms_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAdminReply) ProtoMessage() {}

func (x *GrantAdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAdminReply.ProtoReflect.Descriptor instead.
func (*GrantAdminReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{29}
}

func (x *GrantAdminReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GrantAdminReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetAccessKeyIndexsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessKeyIndexsRequest) Reset() {
	*x = GetAccessKeyIndexsRequest{}
	mi := &file_proto_qkms_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessKeyIndexsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessKeyIndexsRequest) ProtoMessage() {}

func (x *GetAccessKeyIndexsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessKeyIndexsRequest.ProtoReflect.Descriptor instead.
func (*GetAccessKeyIndexsRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{30}
}

func (x *GetAccessKeyIndexsRequest) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

type GetAccessKeyIndexsReply struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	AccessKeys    []*GetAccessKeyIndexsReply_AccessKey `protobuf:"bytes,1,rep,name=AccessKeys,proto3" json:"AccessKeys,omitempty"`
	ErrorCode     uint64                               `protobuf:"varint,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                               `protobuf:"bytes,3,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessKeyIndexsReply) Reset() {
	*x = GetAccessKeyIndexsReply{}
	mi := &file_proto_qkms_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessKeyIndexsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessKeyIndexsReply) ProtoMessage() {}

func (x *GetAccessKeyIndexsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessKeyIndexsReply.ProtoReflect.Descriptor instead.
func (*GetAccessKeyIndexsReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{31}
}

func (x *GetAccessKeyIndexsReply) GetAccessKeys() []*GetAccessKeyIndexsReply_AccessKey {
	if x != nil {
		return x.AccessKeys
	}
	return nil
}

func (x *GetAccessKeyIndexsReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetAccessKeyIndexsReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GenerateCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCredentialRequest) Reset() {
	*x = GenerateCredentialRequest{}
	mi := &file_proto_qkms_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCredentialRequest) ProtoMessage() {}

func (x *GenerateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCredentialRequest.ProtoReflect.Descriptor instead.
func (*GenerateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{32}
}

func (x *GenerateCredentialRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GenerateCredentialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	AppKey        string                 `protobuf:"bytes,3,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	Cert          string                 `protobuf:"bytes,4,opt,name=Cert,proto3" json:"Cert,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCredentialReply) Reset() {
	*x = GenerateCredentialReply{}
	mi := &file_proto_qkms_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCredentialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCredentialReply) ProtoMessage() {}

func (x *GenerateCredentialReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCredentialReply.ProtoReflect.Descriptor instead.
func (*GenerateCredentialReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{33}
}

func (x *GenerateCredentialReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GenerateCredentialReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GenerateCredentialReply) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *GenerateCredentialReply) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *GenerateCredentialReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RevokeCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialRequest) Reset() {
	*x = RevokeCredentialRequest{}
	mi := &file_proto_qkms_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialRequest) ProtoMessage() {}

func (x *RevokeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialRequest.ProtoReflect.Descriptor instead.
func (*RevokeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{34}
}

func (x *RevokeCredentialRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type RevokeCredentialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     uint64                 `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCredentialReply) Reset() {
	*x = RevokeCredentialReply{}
	mi := &file_proto_qkms_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCredentialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCredentialReply) ProtoMessage() {}

func (x *RevokeCredentialReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCredentialReply.ProtoReflect.Descriptor instead.
func (*RevokeCredentialReply) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{35}
}

func (x *RevokeCredentialReply) GetErrorCode() uint64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *RevokeCredentialReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type GetAccessKeyIndexsReply_AccessKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameSpace     string                 `protobuf:"bytes,1,opt,name=NameSpace,proto3" json:"NameSpace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=Environment,proto3" json:"Environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessKeyIndexsReply_AccessKey) Reset() {
	*x = GetAccessKeyIndexsReply_AccessKey{}
	mi := &file_proto_qkms_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessKeyIndexsReply_AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessKeyIndexsReply_AccessKey) ProtoMessage() {}

func (x *GetAccessKeyIndexsReply_AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qkms_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessKeyIndexsReply_AccessKey.ProtoReflect.Descriptor instead.
func (*GetAccessKeyIndexsReply_AccessKey) Descriptor() ([]byte, []int) {
	return file_proto_qkms_proto_rawDescGZIP(), []int{31, 0}
}

func (x *GetAccessKeyIndexsReply_AccessKey) GetNameSpace() string {
	if x != nil {
		return x.NameSpace
	}
	return ""
}

func (x *GetAccessKeyIndexsReply_AccessKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAccessKeyIndexsReply_AccessKey) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

var File_proto_qkms_proto protoreflect.FileDescriptor

const file_proto_qkms_proto_rawDesc = "" +
	"\n" +
	"\x10proto/qkms.proto\x12\n" +
	"qkms_proto\"j\n" +
	"\x14ReadAccessKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x03 \x01(\tR\vEnvironment\"\xf8\x01\n" +
	"\x12ReadAccessKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x1c\n" +
	"\tNameSpace\x18\x03 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12 \n" +
	"\vAKPlaintext\x18\x05 \x01(\tR\vAKPlaintext\x12\x18\n" +
	"\aKeyType\x18\x06 \x01(\tR\aKeyType\x12 \n" +
	"\vEnvironment\x18\a \x01(\tR\vEnvironment\x12\x18\n" +
	"\aVersion\x18\b \x01(\x04R\aVersion\"r\n" +
	"\x1cReadReadableAccessKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x03 \x01(\tR\vEnvironment\"\x80\x02\n" +
	"\x1aReadReadableAccessKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x1c\n" +
	"\tNameSpace\x18\x03 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12 \n" +
	"\vAKPlaintext\x18\x05 \x01(\tR\vAKPlaintext\x12\x18\n" +
	"\aKeyType\x18\x06 \x01(\tR\aKeyType\x12 \n" +
	"\vEnvironment\x18\a \x01(\tR\vEnvironment\x12\x18\n" +
	"\aVersion\x18\b \x01(\x04R\aVersion\"\xcc\x01\n" +
	"\x18GenerateAccessKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aKeyType\x18\x03 \x01(\tR\aKeyType\x12 \n" +
	"\vEnvironment\x18\x04 \x01(\tR\vEnvironment\x12\x1a\n" +
	"\bLifeTime\x18\x05 \x01(\x04R\bLifeTime\x12&\n" +
	"\x0eRotateDuration\x18\x06 \x01(\x04R\x0eRotateDuration\"R\n" +
	"\x16GenerateAccessKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"\x86\x01\n" +
	"\x16RotateAccessKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aKeyType\x18\x03 \x01(\tR\aKeyType\x12 \n" +
	"\vEnvironment\x18\x04 \x01(\tR\vEnvironment\"P\n" +
	"\x14RotateAccessKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"\xec\x01\n" +
	"\x16CreateAccessKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vAKPlaintext\x18\x03 \x01(\tR\vAKPlaintext\x12\x18\n" +
	"\aKeyType\x18\x04 \x01(\tR\aKeyType\x12 \n" +
	"\vEnvironment\x18\x05 \x01(\tR\vEnvironment\x12\x1a\n" +
	"\bLifeTime\x18\x06 \x01(\x04R\bLifeTime\x12&\n" +
	"\x0eRotateDuration\x18\a \x01(\x04R\x0eRotateDuration\"P\n" +
	"\x14CreateAccessKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"\xf4\x01\n" +
	"\x1eCreateReadableAccessKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vAKPlaintext\x18\x03 \x01(\tR\vAKPlaintext\x12\x18\n" +
	"\aKeyType\x18\x04 \x01(\tR\aKeyType\x12 \n" +
	"\vEnvironment\x18\x05 \x01(\tR\vEnvironment\x12\x1a\n" +
	"\bLifeTime\x18\x06 \x01(\x04R\bLifeTime\x12&\n" +
	"\x0eRotateDuration\x18\a \x01(\x04R\x0eRotateDuration\"X\n" +
	"\x1cCreateReadableAccessKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"\xc2\x01\n" +
	"\x16UpdateAccessKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aKeyType\x18\x03 \x01(\tR\aKeyType\x12 \n" +
	"\vAKPlaintext\x18\x04 \x01(\tR\vAKPlaintext\x12 \n" +
	"\vEnvironment\x18\x05 \x01(\tR\vEnvironment\x12\x18\n" +
	"\aVersion\x18\x06 \x01(\x04R\aVersion\"P\n" +
	"\x14UpdateAccessKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"\xd1\x01\n" +
	"+CreateOrUpdateKeyAuthorizationPolicyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x03 \x01(\tR\vEnvironment\x12\x1e\n" +
	"\n" +
	"UserAppkey\x18\x04 \x01(\tR\n" +
	"UserAppkey\x12\x16\n" +
	"\x06Action\x18\x05 \x01(\tR\x06Action\x12\x16\n" +
	"\x06Effect\x18\x06 \x01(\tR\x06Effect\"e\n" +
	")CreateOrUpdateKeyAuthorizationPolicyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"N\n" +
	"\x16CreateNameSpaceRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x02 \x01(\tR\vEnvironment\"P\n" +
	"\x14CreateNameSpaceReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"h\n" +
	"&RotateNameSpaceKeyEncryptionKeyRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12 \n" +
	"\vEnvironment\x18\x02 \x01(\tR\vEnvironment\"`\n" +
	"$RotateNameSpaceKeyEncryptionKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"o\n" +
	"\x1dCreateKeyEncryptionKeyRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x02 \x01(\tR\vEnvironment\x12\x18\n" +
	"\aKeyType\x18\x03 \x01(\tR\aKeyType\"W\n" +
	"\x1bCreateKeyEncryptionKeyReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"L\n" +
	"\x14ReadNameSpaceRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x02 \x01(\tR\vEnvironment\"\xb8\x01\n" +
	"\x12ReadNameSpaceReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x10\n" +
	"\x03KEK\x18\x04 \x01(\tR\x03KEK\x12 \n" +
	"\vEnvironment\x18\x05 \x01(\tR\vEnvironment\x12 \n" +
	"\vOwnerAppkey\x18\x06 \x01(\tR\vOwnerAppkey\"\x86\x01\n" +
	"\x1aUpdateNameSpaceInfoRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x02 \x01(\tR\vEnvironment\x12\x10\n" +
	"\x03KEK\x18\x03 \x01(\tR\x03KEK\x12 \n" +
	"\vOwnerAppkey\x18\x04 \x01(\tR\vOwnerAppkey\"T\n" +
	"\x18UpdateNameSpaceInfoReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"'\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"K\n" +
	"\x0fCreateRoleReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"+\n" +
	"\x11GrantAdminRequest\x12\x16\n" +
	"\x06AppKey\x18\x01 \x01(\tR\x06AppKey\"K\n" +
	"\x0fGrantAdminReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\"9\n" +
	"\x19GetAccessKeyIndexsRequest\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\"\x83\x02\n" +
	"\x17GetAccessKeyIndexsReply\x12M\n" +
	"\n" +
	"AccessKeys\x18\x01 \x03(\v2-.qkms_proto.GetAccessKeyIndexsReply.AccessKeyR\n" +
	"AccessKeys\x12\x1c\n" +
	"\tErrorCode\x18\x02 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x03 \x01(\tR\bErrorMsg\x1a_\n" +
	"\tAccessKey\x12\x1c\n" +
	"\tNameSpace\x18\x01 \x01(\tR\tNameSpace\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vEnvironment\x18\x03 \x01(\tR\vEnvironment\"/\n" +
	"\x19GenerateCredentialRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"\x91\x01\n" +
	"\x17GenerateCredentialReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg\x12\x16\n" +
	"\x06AppKey\x18\x03 \x01(\tR\x06AppKey\x12\x12\n" +
	"\x04Cert\x18\x04 \x01(\tR\x04Cert\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\"1\n" +
	"\x17RevokeCredentialRequest\x12\x16\n" +
	"\x06AppKey\x18\x01 \x01(\tR\x06AppKey\"Q\n" +
	"\x15RevokeCredentialReply\x12\x1c\n" +
	"\tErrorCode\x18\x01 \x01(\x04R\tErrorCode\x12\x1a\n" +
	"\bErrorMsg\x18\x02 \x01(\tR\bErrorMsg2\xcd\r\n" +
	"\x04qkms\x12S\n" +
	"\rReadAccessKey\x12 .qkms_proto.ReadAccessKeyRequest\x1a\x1e.qkms_proto.ReadAccessKeyReply\"\x00\x12k\n" +
	"\x15ReadReadableAccessKey\x12(.qkms_proto.ReadReadableAccessKeyRequest\x1a&.qkms_proto.ReadReadableAccessKeyReply\"\x00\x12_\n" +
	"\x11GenerateAccessKey\x12$.qkms_proto.GenerateAccessKeyRequest\x1a\".qkms_proto.GenerateAccessKeyReply\"\x00\x12q\n" +
	"\x17CreateReadableAccessKey\x12*.qkms_proto.CreateReadableAccessKeyRequest\x1a(.qkms_proto.CreateReadableAccessKeyReply\"\x00\x12Y\n" +
	"\x0fCreateAccessKey\x12\".qkms_proto.CreateAccessKeyRequest\x1a .qkms_proto.CreateAccessKeyReply\"\x00\x12Y\n" +
	"\x0fCreateNameSpace\x12\".qkms_proto.CreateNameSpaceRequest\x1a .qkms_proto.CreateNameSpaceReply\"\x00\x12S\n" +
	"\rReadNameSpace\x12 .qkms_proto.ReadNameSpaceRequest\x1a\x1e.qkms_proto.ReadNameSpaceReply\"\x00\x12Y\n" +
	"\x0fUpdateAccessKey\x12\".qkms_proto.UpdateAccessKeyRequest\x1a .qkms_proto.UpdateAccessKeyReply\"\x00\x12\x98\x01\n" +
	"$CreateOrUpdateKeyAuthorizationPolicy\x127.qkms_proto.CreateOrUpdateKeyAuthorizationPolicyRequest\x1a5.qkms_proto.CreateOrUpdateKeyAuthorizationPolicyReply\"\x00\x12b\n" +
	"\x12GetAccessKeyIndexs\x12%.qkms_proto.GetAccessKeyIndexsRequest\x1a#.qkms_proto.GetAccessKeyIndexsReply\"\x00\x12b\n" +
	"\x12GenerateCredential\x12%.qkms_proto.GenerateCredentialRequest\x1a#.qkms_proto.GenerateCredentialReply\"\x00\x12\\\n" +
	"\x10RevokeCredential\x12#.qkms_proto.RevokeCredentialRequest\x1a!.qkms_proto.RevokeCredentialReply\"\x00\x12J\n" +
	"\n" +
	"GrantAdmin\x12\x1d.qkms_proto.GrantAdminRequest\x1a\x1b.qkms_proto.GrantAdminReply\"\x00\x12\x89\x01\n" +
	"\x1fRotateNameSpaceKeyEncryptionKey\x122.qkms_proto.RotateNameSpaceKeyEncryptionKeyRequest\x1a0.qkms_proto.RotateNameSpaceKeyEncryptionKeyReply\"\x00\x12Y\n" +
	"\x0fRotateAccessKey\x12\".qkms_proto.RotateAccessKeyRequest\x1a .qkms_proto.RotateAccessKeyReply\"\x00\x12e\n" +
	"\x13UpdateNameSpaceInfo\x12&.qkms_proto.UpdateNameSpaceInfoRequest\x1a$.qkms_proto.UpdateNameSpaceInfoReply\"\x00\x12n\n" +
	"\x16CreateKeyEncryptionKey\x12).qkms_proto.CreateKeyEncryptionKeyRequest\x1a'.qkms_proto.CreateKeyEncryptionKeyReply\"\x00B\x0fZ\r./;qkms_protob\x06proto3"

var (
	file_proto_qkms_proto_rawDescOnce sync.Once
	file_proto_qkms_proto_rawDescData []byte
)

func file_proto_qkms_proto_rawDescGZIP() []byte {
	file_proto_qkms_proto_rawDescOnce.Do(func() {
		file_proto_qkms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qkms_proto_rawDesc), len(file_proto_qkms_proto_rawDesc)))
	})
	return file_proto_qkms_proto_rawDescData
}

var file_proto_qkms_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_qkms_proto_goTypes = []any{
	(*ReadAccessKeyRequest)(nil),                        // 0: qkms_proto.ReadAccessKeyRequest
	(*ReadAccessKeyReply)(nil),                          // 1: qkms_proto.ReadAccessKeyReply
	(*ReadReadableAccessKeyRequest)(nil),                // 2: qkms_proto.ReadReadableAccessKeyRequest
	(*ReadReadableAccessKeyReply)(nil),                  // 3: qkms_proto.ReadReadableAccessKeyReply
	(*GenerateAccessKeyRequest)(nil),                    // 4: qkms_proto.GenerateAccessKeyRequest
	(*GenerateAccessKeyReply)(nil),                      // 5: qkms_proto.GenerateAccessKeyReply
	(*RotateAccessKeyRequest)(nil),                      // 6: qkms_proto.RotateAccessKeyRequest
	(*RotateAccessKeyReply)(nil),                        // 7: qkms_proto.RotateAccessKeyReply
	(*CreateAccessKeyRequest)(nil),                      // 8: qkms_proto.CreateAccessKeyRequest
	(*CreateAccessKeyReply)(nil),                        // 9: qkms_proto.CreateAccessKeyReply
	(*CreateReadableAccessKeyRequest)(nil),              // 10: qkms_proto.CreateReadableAccessKeyRequest
	(*CreateReadableAccessKeyReply)(nil),                // 11: qkms_proto.CreateReadableAccessKeyReply
	(*UpdateAccessKeyRequest)(nil),                      // 12: qkms_proto.UpdateAccessKeyRequest
	(*UpdateAccessKeyReply)(nil),                        // 13: qkms_proto.UpdateAccessKeyReply
	(*CreateOrUpdateKeyAuthorizationPolicyRequest)(nil), // 14: qkms_proto.CreateOrUpdateKeyAuthorizationPolicyRequest
	(*CreateOrUpdateKeyAuthorizationPolicyReply)(nil),   // 15: qkms_proto.CreateOrUpdateKeyAuthorizationPolicyReply
	(*CreateNameSpaceRequest)(nil),                      // 16: qkms_proto.CreateNameSpaceRequest
	(*CreateNameSpaceReply)(nil),                        // 17: qkms_proto.CreateNameSpaceReply
	(*RotateNameSpaceKeyEncryptionKeyRequest)(nil),      // 18: qkms_proto.RotateNameSpaceKeyEncryptionKeyRequest
	(*RotateNameSpaceKeyEncryptionKeyReply)(nil),        // 19: qkms_proto.RotateNameSpaceKeyEncryptionKeyReply
	(*CreateKeyEncryptionKeyRequest)(nil),               // 20: qkms_proto.CreateKeyEncryptionKeyRequest
	(*CreateKeyEncryptionKeyReply)(nil),                 // 21: qkms_proto.CreateKeyEncryptionKeyReply
	(*ReadNameSpaceRequest)(nil),                        // 22: qkms_proto.ReadNameSpaceRequest
	(*ReadNameSpaceReply)(nil),                          // 23: qkms_proto.ReadNameSpaceReply
	(*UpdateNameSpaceInfoRequest)(nil),                  // 24: qkms_proto.UpdateNameSpaceInfoRequest
	(*UpdateNameSpaceInfoReply)(nil),                    // 25: qkms_proto.UpdateNameSpaceInfoReply
	(*CreateRoleRequest)(nil),                           // 26: qkms_proto.CreateRoleRequest
	(*CreateRoleReply)(nil),                             // 27: qkms_proto.CreateRoleReply
	(*GrantAdminRequest)(nil),                           // 28: qkms_proto.GrantAdminRequest
	(*GrantAdminReply)(nil),                             // 29: qkms_proto.GrantAdminReply
	(*GetAccessKeyIndexsRequest)(nil),                   // 30: qkms_proto.GetAccessKeyIndexsRequest
	(*GetAccessKeyIndexsReply)(nil),                     // 31: qkms_proto.GetAccessKeyIndexsReply
	(*GenerateCredentialRequest)(nil),                   // 32: qkms_proto.GenerateCredentialRequest
	(*GenerateCredentialReply)(nil),                     // 33: qkms_proto.GenerateCredentialReply
	(*RevokeCredentialRequest)(nil),                     // 34: qkms_proto.RevokeCredentialRequest
	(*RevokeCredentialReply)(nil),                       // 35: qkms_proto.RevokeCredentialReply
	(*GetAccessKeyIndexsReply_AccessKey)(nil),           // 36: qkms_proto.GetAccessKeyIndexsReply.AccessKey
}
var file_proto_qkms_proto_depIdxs = []int32{
	36, // 0: qkms_proto.GetAccessKeyIndexsReply.AccessKeys:type_name -> qkms_proto.GetAccessKeyIndexsReply.AccessKey
	0,  // 1: qkms_proto.qkms.ReadAccessKey:input_type -> qkms_proto.ReadAccessKeyRequest
	2,  // 2: qkms_proto.qkms.ReadReadableAccessKey:input_type -> qkms_proto.ReadReadableAccessKeyRequest
	4,  // 3: qkms_proto.qkms.GenerateAccessKey:input_type -> qkms_proto.GenerateAccessKeyRequest
	10, // 4: qkms_proto.qkms.CreateReadableAccessKey:input_type -> qkms_proto.CreateReadableAccessKeyRequest
	8,  // 5: qkms_proto.qkms.CreateAccessKey:input_type -> qkms_proto.CreateAccessKeyRequest
	16, // 6: qkms_proto.qkms.CreateNameSpace:input_type -> qkms_proto.CreateNameSpaceRequest
	22, // 7: qkms_proto.qkms.ReadNameSpace:input_type -> qkms_proto.ReadNameSpaceRequest
	12, // 8: qkms_proto.qkms.UpdateAccessKey:input_type -> qkms_proto.UpdateAccessKeyRequest
	14, // 9: qkms_proto.qkms.CreateOrUpdateKeyAuthorizationPolicy:input_type -> qkms_proto.CreateOrUpdateKeyAuthorizationPolicyRequest
	30, // 10: qkms_proto.qkms.GetAccessKeyIndexs:input_type -> qkms_proto.GetAccessKeyIndexsRequest
	32, // 11: qkms_proto.qkms.GenerateCredential:input_type -> qkms_proto.GenerateCredentialRequest
	34, // 12: qkms_proto.qkms.RevokeCredential:input_type -> qkms_proto.RevokeCredentialRequest
	28, // 13: qkms_proto.qkms.GrantAdmin:input_type -> qkms_proto.GrantAdminRequest
	18, // 14: qkms_proto.qkms.RotateNameSpaceKeyEncryptionKey:input_type -> qkms_proto.RotateNameSpaceKeyEncryptionKeyRequest
	6,  // 15: qkms_proto.qkms.RotateAccessKey:input_type -> qkms_proto.RotateAccessKeyRequest
	24, // 16: qkms_proto.qkms.UpdateNameSpaceInfo:input_type -> qkms_proto.UpdateNameSpaceInfoRequest
	20, // 17: qkms_proto.qkms.CreateKeyEncryptionKey:input_type -> qkms_proto.CreateKeyEncryptionKeyRequest
	1,  // 18: qkms_proto.qkms.ReadAccessKey:output_type -> qkms_proto.ReadAccessKeyReply
	3,  // 19: qkms_proto.qkms.ReadReadableAccessKey:output_type -> qkms_proto.ReadReadableAccessKeyReply
	5,  // 20: qkms_proto.qkms.GenerateAccessKey:output_type -> qkms_proto.GenerateAccessKeyReply
	11, // 21: qkms_proto.qkms.CreateReadableAccessKey:output_type -> qkms_proto.CreateReadableAccessKeyReply
	9,  // 22: qkms_proto.qkms.CreateAccessKey:output_type -> qkms_proto.CreateAccessKeyReply
	17, // 23: qkms_proto.qkms.CreateNameSpace:output_type -> qkms_proto.CreateNameSpaceReply
	23, // 24: qkms_proto.qkms.ReadNameSpace:output_type -> qkms_proto.ReadNameSpaceReply
	13, // 25: qkms_proto.qkms.UpdateAccessKey:output_type -> qkms_proto.UpdateAccessKeyReply
	15, // 26: qkms_proto.qkms.CreateOrUpdateKeyAuthorizationPolicy:output_type -> qkms_proto.CreateOrUpdateKeyAuthorizationPolicyReply
	31, // 27: qkms_proto.qkms.GetAccessKeyIndexs:output_type -> qkms_proto.GetAccessKeyIndexsReply
	33, // 28: qkms_proto.qkms.GenerateCredential:output_type -> qkms_proto.GenerateCredentialReply
	35, // 29: qkms_proto.qkms.RevokeCredential:output_type -> qkms_proto.RevokeCredentialReply
	29, // 30: qkms_proto.qkms.GrantAdmin:output_type -> qkms_proto.GrantAdminReply
	19, // 31: qkms_proto.qkms.RotateNameSpaceKeyEncryptionKey:output_type -> qkms_proto.RotateNameSpaceKeyEncryptionKeyReply
	7,  // 32: qkms_proto.qkms.RotateAccessKey:output_type -> qkms_proto.RotateAccessKeyReply
	25, // 33: qkms_proto.qkms.UpdateNameSpaceInfo:output_type -> qkms_proto.UpdateNameSpaceInfoReply
	21, // 34: qkms_proto.qkms.CreateKeyEncryptionKey:output_type -> qkms_proto.CreateKeyEncryptionKeyReply
	18, // [18:35] is the sub-list for method output_type
	1,  // [1:18] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_qkms_proto_init() }
func file_proto_qkms_proto_init() {
	if File_proto_qkms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qkms_proto_rawDesc), len(file_proto_qkms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qkms_proto_goTypes,
		DependencyIndexes: file_proto_qkms_proto_depIdxs,
		MessageInfos:      file_proto_qkms_proto_msgTypes,
	}.Build()
	File_proto_qkms_proto = out.File
	file_proto_qkms_proto_goTypes = nil
	file_proto_qkms_proto_depIdxs = nil
}
