package qkms_common

const QKMS_ERROR_CODE_READ_AK_SUCCESS = 200
const QKMS_ERROR_CODE_READ_AK_NOT_EXIST = 201
const QKMS_ERROR_CODE_READ_AK_NOT_AUTHORIZED = 202

const QKMS_ERROR_CODE_CREATE_AK_SUCCESS = 203
const QKMS_ERROR_CODE_CREATE_AK_FAILED = 204
const QKMS_ERROR_CODE_CREATE_AK_ALREADY_EXIST = 205
const QKMS_ERROR_CODE_CREATE_AK_NO_KEK = 206

const QKMS_ERROR_CODE_UPDATE_AK_INFO_MISMATCH = 207
const QKMS_ERROR_CODE_UPDATE_AK_NOT_AUTHORIZED = 208
const QKMS_ERROR_CODE_UPDATE_AK_FAILED = 209
const QKMS_ERROR_CODE_UPDATE_AK_SUCCESS = 210

const QKMS_ERROR_CODE_INTERNAL_KEK_NOT_FOUND = 404
const QKMS_ERROR_CODE_INTERNAL_KEK_VERSION_MISMATCH = 407
const QKMS_ERROR_CODE_INTERNAL_KEK_FOUND = 408

const QKMS_ERROR_CODE_INTERNAL_ERROR = 500
const QKMS_ERROR_CODE_CREATE_KEK_FAILED = 500
const QKMS_ERROR_CODE_CREATE_KEK_SUCCESS = 501

const QKMS_ERROR_CODE_INVALID_OPERATION = 505
const QKMS_ERROR_CODE_READ_INVALID = 506
const QKMS_ERROR_CODE_OPERATION_VALIDATION_UNKNOWN = 507
const QKMS_ERROR_CODE_WRITE_INVALID = 508
const QKMS_ERROR_CODE_READ_VALID = 509
const QKMS_ERROR_CODE_WRITE_VALID = 510

const QKMS_ERROR_CODE_CREATE_KAR_SUCCESS = 511
const QKMS_ERROR_CODE_CREATE_KAR_FAILED = 512

const QKMS_ERROR_CODE_KAR_FIND = 513
const QKMS_ERROR_CODE_KAR_NOT_FIND = 514

const QKMS_ERROR_CODE_CACHE_KAR_UPDATE = 515

const QKMS_ERROR_CODE_KAR_GRANTED = 516
const QKMS_ERROR_CODE_INVALID_CREDENTIALS = 517

const QKMS_ERROR_CODE_GRANT_ROLE_FOR_USER_FAILED = 518
const QKMS_ERROR_CODE_GRANT_ROLE_FOR_USER_SUCCESS = 519
const QKMS_ERROR_CODE_GRANT_NAMESPACE_FOR_ROLE_FAILED = 518
const QKMS_ERROR_CODE_GRANT_NAMESPACE_FOR_ROLE_SUCCESS = 519
const QKMS_ERROR_CODE_CREATE_ROLE_FAILED = 520
const QKMS_ERROR_CODE_CREATE_ROLE_SUCCESS = 521

const QKMS_ERROR_CODE_GET_AK_INDEX_FAILED = 522
const QKMS_ERROR_CODE_GET_AK_INDEX_SUCCESS = 523
